name: Deploy Static Website

on:
  push:
    branches:
      - main # The branch name you are committing the new changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to build branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to build branch
        run: |
          git checkout build
          git rm -r . # Clear the existing files in the build branch
          cp -r ./* ./.* ../  # Copy all files including hidden files
          git add .
          git commit -m "Deploy static website"
          git push origin build